### ISSUE TITLE
UnsupportedClassVersionError: com/github/phisgr/example/Pong$Builder

### ISSUE THREAD

**Issue by debayandesarkar** [phiSgr/gatling-grpc-gradle-demo#2]
Hi,
Thanks for sharing the demo project. Getting the below exception while running the Gatling test . Can you please help?

```

May 06, 2021 2:50:41 PM io.grpc.internal.SerializeReentrantCallsDirectExecutor execute
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@556300f0
java.lang.UnsupportedClassVersionError: com/github/phisgr/example/Pong$Builder
        at com.github.phisgr.example.Pong.toBuilder(Pong.java:244)
        at com.github.phisgr.example.Pong.newBuilder(Pong.java:237)
        at com.github.phisgr.example.DemoServer$1.pingPong(DemoServer.java:13)
        at com.github.phisgr.example.DemoServiceGrpc$MethodHandlers.invoke(DemoServiceGrpc.java:217)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:825)
        at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:231)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerStream$TransportState.deframerClosed(NettyServerStream.java:168)
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233)
        at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191)
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:203)
        at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:258)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:494)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler.access$800(NettyServerHandler.java:101)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:808)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

Regards
Debayan

**Comment by phiSgr** [comment]
Looks like you're building and running the code with different JVM versions. If `clean`ing doesn't help, you'll need to describe the environment and commands you run the test with.

**Comment by debayandesarkar** [comment]
Hi, 
Thanks for your response. I am using SDK 1.8 to build and run the code and used the below commands.

Run the server: ./gradlew run
Run the load test: ./gradlew gatlingRun

Regards
Debayan

**Comment by phiSgr** [comment]
Have you run `./gradlew clean`?

Please also show the output of the following two commands. 

`java -version`
`echo $JAVA_HOME`

**Comment by debayandesarkar** [comment]
Hi,
I am able to run the test successfully now. The issue was in the 2nd terminal where from I started ./gradlew gatlingRun , JAVA_HOME was not set. The test is successful now. However, there one exception thrown related to health check. Please find below the stack trace.

```
➜  gatling-grpc-gradle-demo-master echo $JAVA_HOME

➜  gatling-grpc-gradle-demo-master export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_202`
➜  gatling-grpc-gradle-demo-master ./gradlew gatlingRun                                  
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :gatlingRun
23:34:48.481 [INFO ] c.g.p.g.g.p.GrpcProtocol$ - Making warm up call with method grpc.health.v1.Health/Check
23:34:49.038 [DEBUG] c.g.p.g.g.p.GrpcProtocol$ - Couldn't execute warm up request
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: grpc.health.v1.Health/Check
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:110)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2(grpcProtocol.scala:73)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2$adapted(grpcProtocol.scala:65)
        at scala.Option.foreach(Option.scala:437)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.<init>(grpcProtocol.scala:65)
        at com.github.phisgr.gatling.grpc.protocol.StaticGrpcProtocol.createComponents(grpcProtocol.scala:159)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$$anon$1.$anonfun$newComponents$1(grpcProtocol.scala:113)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:71)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:73)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:73)
        at com.github.phisgr.gatling.grpc.request.Call.<init>(Call.scala:34)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction.<init>(GrpcCallAction.scala:27)
        at com.github.phisgr.gatling.grpc.action.GrpcCallActionBuilder.build(GrpcCallActionBuilder.scala:21)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ChainBuilder.build(StructureBuilder.scala:39)
        at io.gatling.core.action.builder.LoopBuilder.build(LoopBuilder.scala:56)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ScenarioBuilder.build(StructureBuilder.scala:51)
        at io.gatling.core.structure.PopulationBuilder.build(PopulationBuilder.scala:100)
        at io.gatling.core.scenario.SimulationParams.buildScenario(Simulation.scala:170)
        at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:174)
        at scala.collection.immutable.List.map(List.scala:246)
        at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:174)
        at io.gatling.app.Runner.run0(Runner.scala:82)
        at io.gatling.app.Runner.run(Runner.scala:52)
        at io.gatling.app.Gatling$.start(Gatling.scala:80)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
        at io.gatling.app.Gatling$.main(Gatling.scala:37)
        at io.gatling.app.Gatling.main(Gatling.scala)
Simulation com.github.phisgr.exampletest.PingPongSimulation started...
23:34:49.722 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 0, 6622329e-b2b8-407c-8be6-6993659badb7 -> 0, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=

=========================
gRPC response:
status=
OK
body=

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:50.241 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 1, 6622329e-b2b8-407c-8be6-6993659badb7 -> 1, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 1

=========================
gRPC response:
status=
OK
body=
data: 1

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:50.752 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 2, 6622329e-b2b8-407c-8be6-6993659badb7 -> 2, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 2

=========================
gRPC response:
status=
OK
body=
data: 2

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:51.257 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 3, 6622329e-b2b8-407c-8be6-6993659badb7 -> 3, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 3

=========================
gRPC response:
status=
OK
body=
data: 3

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:51.763 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 4, 6622329e-b2b8-407c-8be6-6993659badb7 -> 4, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 4

=========================
gRPC response:
status=
OK
body=
data: 4

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:52.269 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 5, 6622329e-b2b8-407c-8be6-6993659badb7 -> 5, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 5

=========================
gRPC response:
status=
OK
body=
data: 5

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:52.775 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 6, 6622329e-b2b8-407c-8be6-6993659badb7 -> 6, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 6

=========================
gRPC response:
status=
OK
body=
data: 6

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:53.281 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 7, 6622329e-b2b8-407c-8be6-6993659badb7 -> 7, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 7

=========================
gRPC response:
status=
OK
body=
data: 7

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:53.790 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 8, 6622329e-b2b8-407c-8be6-6993659badb7 -> 8, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 8

=========================
gRPC response:
status=
OK
body=
data: 8

<<<<<<<<<<<<<<<<<<<<<<<<<

================================================================================
2021-05-06 23:34:54                                           5s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=9      KO=0     )
> Send message                                             (OK=9      KO=0     )

---- Play Ping Pong ------------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================

23:34:54.297 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 9, 6622329e-b2b8-407c-8be6-6993659badb7 -> 9, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 9

=========================
gRPC response:
status=
OK
body=
data: 9

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:54.804 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 10, 6622329e-b2b8-407c-8be6-6993659badb7 -> 10, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 10

=========================
gRPC response:
status=
OK
body=
data: 10

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:55.313 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 11, 6622329e-b2b8-407c-8be6-6993659badb7 -> 11, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 11

=========================
gRPC response:
status=
OK
body=
data: 11

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:55.818 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 12, 6622329e-b2b8-407c-8be6-6993659badb7 -> 12, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 12

=========================
gRPC response:
status=
OK
body=
data: 12

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:56.323 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 13, 6622329e-b2b8-407c-8be6-6993659badb7 -> 13, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 13

=========================
gRPC response:
status=
OK
body=
data: 13

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:56.830 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 14, 6622329e-b2b8-407c-8be6-6993659badb7 -> 14, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 14

=========================
gRPC response:
status=
OK
body=
data: 14

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:57.334 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 15, 6622329e-b2b8-407c-8be6-6993659badb7 -> 15, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 15

=========================
gRPC response:
status=
OK
body=
data: 15

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:57.842 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 16, 6622329e-b2b8-407c-8be6-6993659badb7 -> 16, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 16

=========================
gRPC response:
status=
OK
body=
data: 16

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:58.346 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 17, 6622329e-b2b8-407c-8be6-6993659badb7 -> 17, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 17

=========================
gRPC response:
status=
OK
body=
data: 17

<<<<<<<<<<<<<<<<<<<<<<<<<
23:34:58.851 [TRACE] c.g.p.g.g.a.GrpcCallAction - 
>>>>>>>>>>>>>>>>>>>>>>>>>>
Request:
Send message: OK 
=========================
Session:
Session(Play Ping Pong,1,Map(data -> 18, 6622329e-b2b8-407c-8be6-6993659badb7 -> 18, timestamp.6622329e-b2b8-407c-8be6-6993659badb7 -> 1620369289095),OK,List(ExitAsapLoopBlock(6622329e-b2b8-407c-8be6-6993659badb7,io.gatling.core.session.package$RichExpression$$$Lambda$329/1210939243@1dcb4189,io.gatling.core.action.Exit@d3b8c67)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$357/1968552224@3384c4af,io.netty.channel.nio.NioEventLoop@38aa816f)
=========================
gRPC request:
headers=
grpc-accept-encoding: gzip
payload=
data: 18

=========================
gRPC response:
status=
OK
body=
data: 18

<<<<<<<<<<<<<<<<<<<<<<<<<

================================================================================
2021-05-06 23:34:59                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=19     KO=0     )
> Send message                                             (OK=19     KO=0     )

---- Play Ping Pong ------------------------------------------------------------
[--------------------------------------------------------------------------]  0%
          waiting: 0      / active: 1      / done: 0     
================================================================================


================================================================================
2021-05-06 23:34:59                                          10s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=19     KO=0     )
> Send message                                             (OK=19     KO=0     )

---- Play Ping Pong ------------------------------------------------------------
[##########################################################################]100%
          waiting: 0      / active: 0      / done: 1     
================================================================================

Simulation com.github.phisgr.exampletest.PingPongSimulation completed in 10 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                         19 (OK=19     KO=0     )
> min response time                                      3 (OK=3      KO=-     )
> max response time                                     44 (OK=44     KO=-     )
> mean response time                                     6 (OK=6      KO=-     )
> std deviation                                          9 (OK=9      KO=-     )
> response time 50th percentile                          4 (OK=4      KO=-     )
> response time 75th percentile                          4 (OK=4      KO=-     )
> response time 95th percentile                         15 (OK=15     KO=-     )
> response time 99th percentile                         38 (OK=38     KO=-     )
> mean requests/sec                                  1.727 (OK=1.727  KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                            19 (100%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 0 (  0%)
================================================================================

Reports generated in 0s.
Please open the following file: /opt/GitHub/gatling-grpc-gradle-demo-master/build/reports/gatling/pingpongsimulation-20210507063448381/index.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 36s
13 actionable tasks: 5 executed, 8 up-to-date
➜  gatling-grpc-gradle-demo-master 



```
Regards
Debayan

**Comment by phiSgr** [comment]
The severity level `DEBUG` tells you that it can be safely ignored.

**Comment by debayandesarkar** [comment]
@phiSgr  Thanks a lot for your prompt support.

Regards
Debayan
