### ISSUE TITLE
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: grpc.health.v1.Health/Check

### ISSUE THREAD

**Issue by mrlov** [phiSgr/gatling-grpc-gradle-demo#5]
When I start the load test with:
`.\gradlew.bat gatlingRun`
the simulation is successful completed, but there is also following exception:
`
08:29:18.115 [DEBUG] c.g.p.g.g.p.GrpcProtocol$ - Couldn't execute warm up request
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: grpc.health.v1.Health/Check
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:123)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2(grpcProtocol.scala:76)        
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.$anonfun$new$2$adapted(grpcProtocol.scala:68)
        at scala.Option.foreach(Option.scala:437)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$GrpcComponent.<init>(grpcProtocol.scala:68)
        at com.github.phisgr.gatling.grpc.protocol.StaticGrpcProtocol.createComponents(grpcProtocol.scala:168)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$$anon$1.$anonfun$newComponents$1(grpcProtocol.scala:116)   
        at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:71)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:73)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:73)
        at com.github.phisgr.gatling.grpc.request.Call.<init>(Call.scala:19)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction.<init>(GrpcCallAction.scala:28)
        at com.github.phisgr.gatling.grpc.action.GrpcCallActionBuilder.build(GrpcCallActionBuilder.scala:19)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ChainBuilder.build(StructureBuilder.scala:43)
        at io.gatling.core.action.builder.LoopBuilder.build(LoopBuilder.scala:58)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ScenarioBuilder.build(StructureBuilder.scala:55)
        at io.gatling.core.structure.PopulationBuilder.build(PopulationBuilder.scala:100)
        at io.gatling.core.scenario.SimulationParams.buildScenario(Simulation.scala:199)
        at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:203)
        at scala.collection.immutable.List.map(List.scala:246)
        at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:203)
        at io.gatling.app.Runner.run0(Runner.scala:77)
        at io.gatling.app.Runner.run(Runner.scala:49)
        at io.gatling.app.Gatling$.start(Gatling.scala:87)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
        at io.gatling.app.Gatling$.main(Gatling.scala:38)
        at io.gatling.app.Gatling.main(Gatling.scala)
Simulation com.github.phisgr.exampletest.PingPongSimulation started...
`

I would expect no exception should be thrown....

**Comment by phiSgr** [comment]
It's a `DEBUG` log about a `warm up request`. Which part of that do you more elaboration?
