### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by mrlov** [phiSgr/gatling-grpc-gradle-demo#6]
I have tried to update the dependencies in build.gradle to the newest versions of gatling* , grpc* etc but I failed with following error:

`
> Task :gatlingRun
10:56:57.865 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.NoSuchMethodError: io.gatling.netty.util.Transports.newSocketChannelFactory(Z)Lio/netty/channel/ChannelFactory;
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$.setEventLoopGroup(grpcProtocol.scala:127)
        at com.github.phisgr.gatling.grpc.protocol.StaticGrpcProtocol.createComponents(grpcProtocol.scala:166)
        at com.github.phisgr.gatling.grpc.protocol.GrpcProtocol$$anon$1.$anonfun$newComponents$1(grpcProtocol.scala:119)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:67)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:69)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
        at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:69)
        at com.github.phisgr.gatling.grpc.request.Call.<init>(Call.scala:19)
        at com.github.phisgr.gatling.grpc.request.UnaryResponse.<init>(UnaryResponse.scala:16)
        at com.github.phisgr.gatling.grpc.request.UnaryResponse.<init>(UnaryResponse.scala:27)
        at com.github.phisgr.gatling.grpc.action.GrpcCallAction.<init>(GrpcCallAction.scala:26)
        at com.github.phisgr.gatling.grpc.action.GrpcCallActionBuilder.build(GrpcCallActionBuilder.scala:19)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ChainBuilder.build(StructureBuilder.scala:44)
        at io.gatling.core.action.builder.LoopBuilder.build(LoopBuilder.scala:57)
        at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
        at io.gatling.core.structure.BuildAction.build$(BuildAction.scala:26)
        at io.gatling.core.structure.ScenarioBuilder.build(StructureBuilder.scala:57)
        at io.gatling.core.structure.PopulationBuilder.build(PopulationBuilder.scala:93)
        at io.gatling.core.scenario.SimulationParams.buildScenario(Simulation.scala:195)
        at io.gatling.core.scenario.SimulationParams.$anonfun$scenarioFlows$1(Simulation.scala:199)
        at scala.collection.immutable.List.map(List.scala:246)
        at io.gatling.core.scenario.SimulationParams.scenarioFlows(Simulation.scala:199)
        at io.gatling.app.Runner.load(Runner.scala:89)
        at io.gatling.app.Runner.run(Runner.scala:57)
        at io.gatling.app.Gatling$.start(Gatling.scala:89)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:51)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
`

Could you update the dependencies?

**Comment by phiSgr** [comment]
See https://github.com/phiSgr/gatling-grpc/pull/73
